openapi: 3.1.1
info:
  title: MarketSignal API
  version: 1.0.0

components:
  schemas:
    IanaTimezone:
      type: string
      example: Europe/Warsaw

    DataProvider:
      type: string
      example: alphaVantage

    Indicator:
      type: string
      example: SMA_7

    MessageResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string
          example: Data provider not found.

    InstrumentId:
      type: object
      required: [mic, symbol]
      properties:
        mic:
          type: string
          example: XNAS
        symbol:
          type: string
          example: AAPL

    JobId:
      type: number
      format: int64

    GetJobResultResponse:
      oneOf:
        - $ref: "#/components/schemas/GetJobResultPendingResponse"
        - $ref: "#/components/schemas/GetJobResultSuccessResponse"
        - $ref: "#/components/schemas/GetJobResultFailureResponse"
      discriminator:
        propertyName: status
        mapping:
          pending: "#/components/schemas/GetJobResultPendingResponse"
          success: "#/components/schemas/GetJobResultSuccessResponse"
          failure: "#/components/schemas/GetJobResultFailureResponse"

    GetJobResultPendingResponse:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [pending]

    GetJobResultSuccessResponse:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [success]

    GetJobResultFailureResponse:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [failure]
        message:
          type: string

    CalcIndicatorValuesRequest:
      type: object
      required: [instrumentId, dataProvider]
      properties:
        instrumentId:
          $ref: "#/components/schemas/InstrumentId"
        dataProvider:
          $ref: "#/components/schemas/DataProvider"

    GetIndicatorValuesResponse:
      type: object
      required: [rows]
      properties:
        rows:
          type: array
          items:
            type: object
            required: [time, value]
            properties:
              time:
                type: string
                format: date-time
              value:
                type: number
                format: double

paths:
  /instruments/{instrumentId}/raw-data/pull:
    post:
      tags: [Instruments]
      operationId: pullInstrumentRawData
      summary: Downloads new raw data about the instrument from an external source and stores it locally.
      security: []
      parameters:
        - in: query
          name: instrumentId
          required: true
          schema:
            $ref: "#/components/schemas/InstrumentId"
        - in: query
          name: dataProvider
          required: true
          schema:
            $ref: "#/components/schemas/DataProvider"
        - in: query
          name: from
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "202":
          description: Successfully started a job.
          content:
            application/json:
              schema:
                type: object
                required: [jobId]
                properties:
                  jobId:
                    $ref: "#/components/schemas/JobId"
        "400":
          description: Bad request.
        "404":
          description: Instrument or data provider not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /instruments/{instrumentId}/indicators/{indicator}/values:
    get:
      tags: [Indicators]
      operationId: getIndicatorValues
      summary: get indicator values for chosen instrument, data provider and time range.
      security: []
      parameters:
        - in: path
          name: instrumentId
          required: true
          schema:
            $ref: "#/components/schemas/InstrumentId"
        - in: path
          name: indicator
          required: true
          schema:
            $ref: "#/components/schemas/Indicator"
        - in: query
          name: dataProvider
          required: true
          schema:
            $ref: "#/components/schemas/DataProvider"
        - in: query
          name: from
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Successfully retrieve indicator values.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetIndicatorValuesResponse"
        "400":
          description: Bad request.
        "404":
          description: Instrument or data provider not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /instruments/{instrumentId}/indicators/{indicator}/calculate-values:
    post:
      tags: [Indicators]
      operationId: calculateIndicatorValues
      summary: calculate indicator values for chosen instrument and data provider.
      security: []
      parameters:
        - in: path
          name: instrumentId
          required: true
          schema:
            $ref: "#/components/schemas/InstrumentId"
        - in: path
          name: indicator
          required: true
          schema:
            $ref: "#/components/schemas/Indicator"
        - in: query
          name: dataProvider
          required: true
          schema:
            $ref: "#/components/schemas/DataProvider"
      responses:
        "200":
          description: Successfully start a calculation job.
          content:
            application/json:
              schema:
                type: object
                required: [jobId]
                properties:
                  jobId:
                    $ref: "#/components/schemas/JobId"
        "400":
          description: Bad request.
        "404":
          description: Instrument or data provider not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"

  /indicators/value-calculation/jobs/{jobId}/result:
    get:
      tags: [Indicators]
      operationId: getCalculateIndicatorValuesJobResult
      summary: Get the result of a indicator calculation job.
      security: []
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            $ref: "#/components/schemas/JobId"
      responses:
        "200":
          description: Successfully retrieve job result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetJobResultResponse"
        "400":
          description: Bad request.
        "404":
          description: Job not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
